#!/bin/bash
#ask for name and description work out the date
echo "Enter a Unique project name"
read prjnm
echo "Enter a short porject description"
read prjdesc
now=`date +"%Y-%m-%d"`

mkdir /home/jammers/Project_archive/$prjnm

#change_log
echo "***********************************" >> /home/jammers/Project_archive/$prjnm/changelog.md
echo "$prjnm changelog file" >> /home/jammers/Project_archive/$prjnm/changelog.md
echo "created by James Ware licenced GNU General Public License" >> /home/jammers/Project_archive/$prjnm/changelog.md
echo "please see the gnu licence attached or visit - https://www.gnu.org/licenses/gpl-3.0.en.html" >> /home/jammers/Project_archive/$prjnm/changelog.md
echo "project created ${now}" >> /home/jammers/Project_archive/$prjnm/changelog.md
echo "***********************************" >> /home/jammers/Project_archive/$prjnm/changelog.md
echo "format;" >> /home/jammers/Project_archive/$prjnm/changelog.md
echo "DATE YYYY-MM-DD - changes made" >> /home/jammers/Project_archive/$prjnm/changelog.md
echo "***********************************" >> /home/jammers/Project_archive/$prjnm/changelog.md

# echo "#!/bin/bash">> /home/jammers/Project_archive/$prjnm/logedit
# echo "now=`date +"%Y-%m-%d"` ">> /home/jammers/Project_archive/$prjnm/logedit
# echo echo "What did you change?"/home/jammers/Project_archive/$prjnm/logedit
# echo read edit /home/jammers/Project_archive/$prjnm/logedit
# echo echo "${now} - $edit" >> /home/jammers/Project_archive/$prjnm/changelog.md

echo "***********************************" >> /home/jammers/Project_archive/$prjnm/readme.md
echo "$prjnm readme file" >> /home/jammers/Project_archive/$prjnm/readme.md
echo "created by James Ware licenced GNU General Public License" >> /home/jammers/Project_archive/$prjnm/changelog.md
echo "project created ${now}" >> /home/jammers/Project_archive/$prjnm/changelog.md
echo "***********************************" >> /home/jammers/Project_archive/$prjnm/readme.md
echo $prjdesc >> /home/jammers/Project_archive/$prjnm/readme.md


echo "---
alias:
hasAnki: false
isLinked: LOW
projectType:
isMoc: false
isProject: true
isChunk: false
isTask: false
status: planning
priority: 4
status:">> /home/jammers/Zettel/GoblinKnows/FOREST/01-Green_House/test.md
echo "date: $now">> /home/jammers/Zettel/GoblinKnows/FOREST/01-Green_House/test.md
echo "---">> /home/jammers/Zettel/GoblinKnows/FOREST/01-Green_House/test.md
echo "# $prjnm">> /home/jammers/Zettel/GoblinKnows/FOREST/01-Green_House/test.md
echo "#### Project Read me">> /home/jammers/Zettel/GoblinKnows/FOREST/01-Green_House/test.md
echo $prjdesc>> /home/jammers/Zettel/GoblinKnows/FOREST/01-Green_House/test.md
echo "
#### Brief

#### Materials

#### Write up
 
###### Licencing
This project is licenced under the [GNU GENERAL PUBLIC LICENCE](https://www.gnu.org/licenses/gpl-3.0.en.html)

---
**Related:**
**Tags:**">> /home/jammers/Zettel/GoblinKnows/FOREST/01-Green_House/test.md
echo "**Resources:** [$prjnm folder](file:///home/jammers/Project_archive/$prjnm)">>/home/jammers/Zettel/GoblinKnows/FOREST/01-Green_House/test.md



