#!/bin/bash
#ask for name and description work out the date
echo "Enter a Unique project name"
read prjnm
echo "Enter a short project description"
read prjdesc
now=`date +"%Y-%m-%d"`

mkdir /home/jammers/Project_archive/$prjnm

#change_log
echo "***********************************" >> /home/jammers/Project_archive/$prjnm/changelog.md
echo "$prjnm changelog file" >> /home/jammers/Project_archive/$prjnm/changelog.md
echo "created by James Ware licenced GNU General Public License" >> /home/jammers/Project_archive/$prjnm/changelog.md
echo "please see the gnu licence attached or visit - https://www.gnu.org/licenses/gpl-3.0.en.html" >> /home/jammers/Project_archive/$prjnm/changelog.md
echo "project created ${now}" >> /home/jammers/Project_archive/$prjnm/changelog.md
echo "***********************************" >> /home/jammers/Project_archive/$prjnm/changelog.md
echo "format;" >> /home/jammers/Project_archive/$prjnm/changelog.md
echo "DATE YYYY-MM-DD - changes made" >> /home/jammers/Project_archive/$prjnm/changelog.md
echo "***********************************" >> /home/jammers/Project_archive/$prjnm/changelog.md

# echo "#!/bin/bash">> /home/jammers/Project_archive/$prjnm/logedit
# echo "now=`date +"%Y-%m-%d"` ">> /home/jammers/Project_archive/$prjnm/logedit
# echo echo "What did you change?"/home/jammers/Project_archive/$prjnm/logedit
# echo read edit /home/jammers/Project_archive/$prjnm/logedit
# echo echo "${now} - $edit" >> /home/jammers/Project_archive/$prjnm/changelog.md

echo "***********************************" >> /home/jammers/Project_archive/$prjnm/readme.md
echo "$prjnm readme file" >> /home/jammers/Project_archive/$prjnm/readme.md
echo "created by James Ware licenced GNU General Public License" >> /home/jammers/Project_archive/$prjnm/changelog.md
echo "project created ${now}" >> /home/jammers/Project_archive/$prjnm/changelog.md
echo "***********************************" >> /home/jammers/Project_archive/$prjnm/readme.md
echo $prjdesc >> /home/jammers/Project_archive/$prjnm/readme.md


echo "---
alias:
author:
hasAnki: 
ISBN:
isLinked: LOW
isList: 
isMan: 
isMoc: 
isProject: true
priority: 4
projectMain: $prjnm
projectType: 
reviewed: 1
status: planning
subject: 
tags: 
temporal:
type: project
date: $now
---
# $prjnm">> /home/jammers/Zettel/GoblinKnows/FOREST/01-Green_House/$prjnm.md
echo "$prjdesc">> /home/jammers/Zettel/GoblinKnows/FOREST/01-Green_House/$prjnm.md
echo "">> /home/jammers/Zettel/GoblinKnows/FOREST/01-Green_House/$prjnm.md
echo "#### Brief">> /home/jammers/Zettel/GoblinKnows/FOREST/01-Green_House/$prjnm.md
echo "">> /home/jammers/Zettel/GoblinKnows/FOREST/01-Green_House/$prjnm.md
echo "#### Materials">> /home/jammers/Zettel/GoblinKnows/FOREST/01-Green_House/$prjnm.md
echo "">> /home/jammers/Zettel/GoblinKnows/FOREST/01-Green_House/$prjnm.md
echo "#### Write up">> /home/jammers/Zettel/GoblinKnows/FOREST/01-Green_House/$prjnm.md
echo " ">> /home/jammers/Zettel/GoblinKnows/FOREST/01-Green_House/$prjnm.md
echo "#### Task Pane">> /home/jammers/Zettel/GoblinKnows/FOREST/01-Green_House/$prjnm.md
echo "\`\`\`dataview">> /home/jammers/Zettel/GoblinKnows/FOREST/01-Green_House/$prjnm.md
echo "task">> /home/jammers/Zettel/GoblinKnows/FOREST/01-Green_House/$prjnm.md
echo "from \"FOREST\"">> /home/jammers/Zettel/GoblinKnows/FOREST/01-Green_House/$prjnm.md
echo "where !completed & projectMain = \"$prjnm\" & type = \"taskList\"">> /home/jammers/Zettel/GoblinKnows/FOREST/01-Green_House/$prjnm.md
echo "">> /home/jammers/Zettel/GoblinKnows/FOREST/01-Green_House/$prjnm.md
echo "\`\`\`">> /home/jammers/Zettel/GoblinKnows/FOREST/01-Green_House/$prjnm.md
echo "---">> /home/jammers/Zettel/GoblinKnows/FOREST/01-Green_House/$prjnm.md
echo "This project is licensed under the [GNU GENERAL PUBLIC LICENCE](https://www.gnu.org/licenses/gpl-3.0.en.html)">> /home/jammers/Zettel/GoblinKnows/FOREST/01-Green_House/$prjnm.md
echo "**Related:**">> /home/jammers/Zettel/GoblinKnows/FOREST/01-Green_House/$prjnm.md
echo "**Resources:** [$prjnm folder](file:///home/jammers/Project_archive/$prjnm)">>/home/jammers/Zettel/GoblinKnows/FOREST/01-Green_House/$prjnm.md

echo "---
alias:
author:
hasAnki: 
ISBN:
isLinked: LOW
isList: 
isMan: 
isMoc: 
isProject: true
priority: 4
projectMain: $prjnm
projectType: 
reviewed: 1
status: 
subject: 
tags: 
temporal:
type: taskList
date: $now
---
# $prjnm-taskList
## [[$prjnm]]" >>/home/jammers/Zettel/GoblinKnows/FOREST/01-Green_House/$prjnm-taskList.md
