#!/bin/bash
# generate a random password
if [[ "$#" -eq 0 || "$1" == "--help" ]]
then
    echo "Usage: $0 DELAY"
    echo " to pause for DELAY seconds"
    exit 1
fi

#LENGTH=40
CHARS=qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM1234567890

# for i in $(seq 1 $LENGTH); do
#         echo -n "${CHARS:RANDOM%${#CHARS}:1}"
#     done
#     echo
# for (( i=1; i<=$1; ${CHARS:RANDOM%${#CHARS}:1}))
# do
# echo -n 
# done

for ((i=1; i<$1; i++)) do
echo -n "${CHARS:RANDOM%${#CHARS}:1}"
#  echo $i
done
echo
